name: attrpred-env
channels:
  - pytorch
dependencies:
  - python=3.8
  - pip
  - build
  - gcsfs
  - ipykernel
  - numpy
  - matplotlib
  - pyyaml
  - pytorch
  - torchvision
  - cpuonly  # 'cudatoolkit=11.3' if you have a gpu else 'cpuonly'
  - pandas
  - fsspec
  - tensorboard
  - scikit-learn
  - tqdm
  - tabulate
  - pytest
  - pytest-cov
  - pytest-mock
  - mypy
  - pylint
  - black
  - isort
  - pip:
    - torch-tb-profiler
    - apache-beam[gcp,docs,test,dataframe]